//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAQY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int id { get; set; }
        public string title { get; set; }
        public string details { get; set; }
        public Nullable<int> price { get; set; }
        public string img { get; set; }
        public string date { get; set; }
        public Nullable<int> dis { get; set; }
    }
}
